---
# file: site.yml
- hosts:
      - mc-dev-01.v6-400.ber1.pussy-hosting.berlin
  roles:
      - role_app_minecraft
      - role_app_geyser
      # Need public ip for letsencrypt
      # - role_app_nginx_letsencrypt_proxy
